config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
  member do
    delete 'unsign'
    end
  end
  resources :employees
  resources :departments
  devise_for :users, controllers: { registrations: 'users/registrations' }
  #get 'home/index'
  root 'home#index'
  #root 'employees#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :department
	belongs_to :user
	has_many :employees_tickets
	has_many :tickets, through: :employees_tickets
	has_many :tickets
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :aktualny

  # GET /employees or /employees.json

  def index
    @employees = Employee.all
  end

  def aktualny
    @aktualny = current_user.employee if current_user.present?
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Dane zostały dodane poprawnie" }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Dane zostały poprawnie zaktualizowane." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Pracownik został usunięty." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :user_id, :department_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">

  <p style="color: white;">
    <strong>Imię:  </strong>
    <%= employee.first_name %>
  </p>

  <p style="color: white;">
    <strong>Nazwisko:</strong>
    <%= employee.last_name %>
  </p>


</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Imię, style: "display: block; color: white;" %>
    <%= form.text_field :first_name, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;"  %>
  </div>

  <div>
    <%= form.label :Nazwisko, style: "display: block; color: white;" %>
    <%= form.text_field :last_name , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :employee_user_id, value:current_user.id, type: :hidden %>
  </div>

  <div style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" >
    <%= form.label :Dział, style: "display: block; color: white;" %>
    <%= form.collection_select :department_id, Department.all, :id, :department_name, prompt: "Wybierz dział" , style: "background-color: ##db1212;"%>
  </div></br>

  <div>
    <%= form.submit "Zmień dane" , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1 style="color: white;">Edytowanie danych użytkownika</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Pokaż aktualne dane", @employee, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;"  %> |
  <%= link_to "Wróć", employees_path , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
</div>

app/views/employees/index.html.erb
<h1 style="color: white;">Dane osobowe</h1>

<div id="employees">

  <% @employees.each do |employee| %>

    <% if employee.user == current_user %>

      <%= render employee %>
      <p>
        <%= button_to "Pokaż dane osobowe", employee, method: :get, class: "btn btn-dark" %>
      </p>
    <% end %>
  <% end %>

</div>
<% unless @employees.any? { |employee| employee.user == current_user } %>
  <%= button_to "Dodaj dane osobowe", new_employee_path, method: :get, class: "btn btn-dark" %>
<% end %>

app/views/employees/new.html.erb
<h1 style="color: white;">Podaj dane osobowe</h1>

<%= render "form", employee: @employee %>

<br>


<!-- <div> -->
<!--   <%= link_to "Back to employees", employees_path %> -->
<!-- </div> -->

app/views/employees/show.html.erb
<%= render @employee %>

<div>
 <%= button_to "Edytuj dane", edit_employee_path(@employee), method: :get, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;"%> |

 <%= button_to "Wróć", employees_path , method: :get, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
<hr style="height:1px;" />
 <%= button_to "Usuń dane osobowe", @employee, method: :delete, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;", data: { confirm: 'Are you sure?' } %>
</div>