config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
  member do
    delete 'unsign'
    end
  end
  resources :employees
  resources :departments
  devise_for :users, controllers: { registrations: 'users/registrations' }
  #get 'home/index'
  root 'home#index'
  #root 'employees#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :employees
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :aktualny

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  def aktualny
    @aktualny = current_user.employee if current_user.present?
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy!

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:department_name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <div style="color: white; font-weight: bold;">
    <%= department.department_name %>
  </div>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="color: white;">
    <%= form.label :"Podaj nazwę nowego działu", style: "display: block" %>
    <%= form.text_field :department_name,  style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
<hr style="margin-top: 1px; margin-bottom: 1px;" />
  </div>

  <div>
    <%= form.submit "Utwórz", style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1 style="color: white;">Edytuj Dział</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Pokaż dział", @department , class: "btn btn-dark"%> |
  <%= link_to "Wróć do działów", departments_path, class: "btn btn-dark" %>
</div>

app/views/departments/index.html.erb
<div id="departments">
 <% @departments.each do |department| %>
    <%= render department %>
      <%= button_to "Pokaż Dział", department, method: :get , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
    
 <% end %>
</div>
<hr style="margin-top: 10px; margin-bottom: 40px;" />
<%= button_to "Dodaj Nowy Dział", new_department_path, method: :get, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>

app/views/departments/new.html.erb
<h1 style="color: white;">Utwórz nowy dział</h1>

<%= render "form", department: @department %>

<br>
<hr style="margin-top: 1px; margin-bottom: 1px;" />
<div>
 <%= button_to "Wróć do Działów", departments_path, method: :get, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
</div>

app/views/departments/show.html.erb
<%= render @department %>

<div>
<%= button_to "Edytuj dział", edit_department_path(@department), method: :get , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;"  %> |
 <%= button_to "Wróć do działów", departments_path , method: :get , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>

<hr style="margin-top: 1px; margin-bottom: 1px;" />
  <%= button_to "Usuń dział", @department, method: :delete, style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %>
</div>