config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
  member do
    delete 'unsign'
    end
  end
  resources :employees
  resources :departments
  devise_for :users, controllers: { registrations: 'users/registrations' }
  #get 'home/index'
  root 'home#index'
  #root 'employees#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	has_many :employees_tickets
	has_many :employees, through: :employees_tickets
	belongs_to :employee
	has_one_attached :image
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy unsign]
  before_action :authenticate_user!
  before_action :set_current_employee
  before_action :set
  before_action :aktualny

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
    @employees_tickets = EmployeesTicket.all
  end

  def unsign
    unsign = EmployeesTicket.where(employee_id: @aktualny.id, ticket_id: @ticket.id)
    if unsign.present?
    unsign.delete_all
    flash[:notice] = 'Przypisano nowe zgloszenie'
    end
    redirect_to tickets_path
  end

  def aktualny
    @aktualny = current_user.employee if current_user.present?
  end

  def set_current_employee
    # Ustawia obiekt @employee na podstawie danych zalogowanego użytkownika
    @employee = current_user.employee
  end

  def set
    @user = User.all
    @emp = Employee.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
    @employees_tickets = EmployeesTicket.all
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Zgłoszenie utworzone pomyślnie." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Zgłoszenie zostało zaktualizowane." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy!

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Zgłoszenie usunięte pomyślnie." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:employee_id,:status, :description, :image)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :Opis, style: "display: block; color: white;" %>

    <%= form.text_area :description, rows: 20, cols: 100 , style: "background-color: #343a40;color: white;"%>
  </div>

  <div>
<%= form.label :"Dodaj zdjęcie", style: "display: block; color: white;" %>
    <%= form.file_field :image , style: "background-color: #343a40;color: white;", accept: 'image/png, image/gif, image/jpeg'%>
  </div>

  <% if cannot? :department_id_1, @aktualny %>
  <div>
    <%= form.text_field :status, value: 'Nowy', type: :hidden %>
  </div>
  <% end %>

  <div>
    <%= form.number_field :employee_id, value:@employee.id, type: :hidden %>
  </div>
<hr style="margin-top: 10px; margin-bottom: 1px;" />

  <% if cannot? :department_id_1, @aktualny %>
  <div>
    <%= form.submit "Aktualizuj zgłoszenie"  , class: "btn btn-dark"%>
  </div>
  <% end %>
  
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">

<% if can? :department_id_1, @aktualny %>
    <% if ticket.status == 'Nowy' && !@employees_tickets.exists?(employee_id: @aktualny) %>
          <% @employees_tickets.create(employee_id: @aktualny.id, ticket_id: ticket.id) %>
    <% end %>

    <% if @employees_tickets.exists?(ticket_id: ticket.id) %>



<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Imie</th>
      <th scope="col">Nazwisko</th>
      <th scope="col">Email</th>
      <th scope="col">Data utworzenia</th>
      <th scope="col">Data modyfikacji</th>
      <th scope="col">Stan</th>
      <th scope="col">Przejdź do zgłoszenia</th>
      
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @emp.find(ticket.employee_id).first_name %></td>
      <td><%= @emp.find(ticket.employee_id).last_name %></td>
       <td><%= @user.find(@emp.find(ticket.employee_id).user_id).email %></td>
      <td><%= ticket.created_at %></td>
      <td><%= ticket.updated_at %></td>
      <td><%= ticket.status %></td>
      <td><%= button_to "Pokaz zgłoszenie", ticket, method: :get , style: "background-color: #534d75; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %></td>
     
      <tr>
      <th scope="row">Opis</th>
 
      <td colspan="6"><%= ticket.description %></td>
      <tr>
      <th scope="row">Zdjęcie</th>
 
      <td colspan="6">
    <%if ticket.image.attached?%>
    <div style="text-align: center;">
    <%= image_tag(ticket.image, style:"height: 500px;") %>
    <% end %>
      </td>
    </tr>
  
   </tr>
  </tbody>
</table>

<% end %>
  <% else %>

  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Imie</th>
        <th scope="col">Nazwisko</th>
        <th scope="col">Email</th>
        <th scope="col">Data utworzenia</th>
        <th scope="col">Data modyfikacji</th>
        <th scope="col">Stan</th>
        <th scope="col">Przejdź do zgłoszenia</th>
        
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @emp.find(ticket.employee_id).first_name %></td>
        <td><%= @emp.find(ticket.employee_id).last_name %></td>
         <td><%= @user.find(@emp.find(ticket.employee_id).user_id).email %></td>
        <td><%= ticket.created_at %></td>
        <td><%= ticket.updated_at %></td>
        <td><%= ticket.status %></td>
        <td><%= button_to "Pokaz zgłoszenie", ticket, method: :get , style: "background-color: #534d75; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;" %></td>
       
        <tr>
        <th scope="row">Opis</th>
   
        <td colspan="6"><%= ticket.description %></td>
        <tr>
        <th scope="row">Zdjęcie</th>
   
        <td colspan="6">
      <%if ticket.image.attached?%>
      <div style="text-align: center;">
      <%= image_tag(ticket.image, style:"height: 500px;") %>
      <% end %>
        </td>
      </tr>
    
     </tr>
    </tbody>
  </table>

  <% end %>

</div>

app/views/tickets/edit.html.erb
<h1 style="color: white;">Edytowanie zgłoszenia</h1>

<% if can? :department_id_1, @aktualny %>

<hr style="margin-top: 10px; margin-bottom: 1px;" />

<hr style="margin-top: 10px; margin-bottom: 1px;" />

<%= form_for @ticket, url: ticket_path(@ticket), method: :put do |f| %>

  <div style="color: white",>Dodaj rozwiązanie</div>

  <hr style="margin-top: 10px; margin-bottom: 1px;" />
  <%= f.text_area :description, rows: 20, cols: 100,  style: "background-color: #343a40;color: white;" %>

  <hr style="margin-top: 10px; margin-bottom: 1px;" />
  <%= f.button "Dodaj rozwiazanie", class: "btn btn-dark" %>
  <% end %>

<hr style="margin-top: 10px; margin-bottom: 1px;" />
<% end %>

<%= render "form", editing: true, ticket: @ticket %>

<br>

<div>

  <%= form_for @ticket, url: ticket_path(@ticket), method: :put do |f| %>
  <%= f.hidden_field :status, value: 'W trakcie' %>
  <%= f.button "Zmien status na: W trakcie rozwiazywania", class: "btn btn-dark" %>
  <% end %>


</br>

  <%= form_for @ticket, url: ticket_path(@ticket), method: :put do |f| %>
  <%= f.hidden_field :status, value: 'Problem rozwiazany' %>
  <%= f.submit "Oznacz jako rozwiązane", class: "btn btn-dark" %>
  <% end %>

<hr style="margin-top: 10px; margin-bottom: 1px;" />
  <%= link_to "Pokaż zgłoszenie", @ticket , class: "btn btn-dark" %> |
  <%= link_to "Wróć do zgłoszeń", tickets_path , class: "btn btn-dark" %>

<hr style="margin-top: 10px; margin-bottom: 1px;" />
  <%= button_to 'Rozwiaz nastepne zgloszenie', unsign_ticket_path(@ticket), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %>

<hr style="margin-top: 10px; margin-bottom: 1px;" />


</div>

app/views/tickets/index.html.erb
<h1 style="color: white;">Zgłoszenia</h1>

<div id="tickets">
  <% @tickets.each do |ticket| %>


  <% if can? :department_id_1, @aktualny %>
   <div class="page-divider"></div>

      <%= render ticket %>

  <% elsif @employee.user == current_user && ticket.employee_id == @employee.id %>
  
    <%= render ticket %>
    <% end %>
  <% end %>
 
</div>

<% if cannot? :department_id_1, @aktualny %>
  <%= link_to "Nowe zgłoszenie", new_ticket_path , class: "btn btn-dark"%>
<% end %>

app/views/tickets/new.html.erb
<h1 style="color: white;">Nowe zgłoszenie</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Wroc do zgłoszeń", tickets_path , class: "btn btn-dark"%>
</div>

app/views/tickets/show.html.erb
<%= render @ticket %>

<div>
<% if can? :department_id_1, @aktualny %>

  <%= button_to "Edytuj zgłoszenie", edit_ticket_path(@ticket) , method: :get , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;"%>
<hr style="margin-top: 10px; margin-bottom: 1px;" />

<% end %>
  <%= button_to "Wróć do zgłoszeń", tickets_path , method: :get , style: "background-color: #343a40; color: white; padding: 5px 10px; border: none; border-radius: 5px; cursor: pointer;"%>
<hr style="margin-top: 10px; margin-bottom: 1px;" />

  <%= button_to "Usuń zgłoszenie", @ticket, method: :delete, class:"btn btn-dark" %>
</div>